---
downloads: ~/.ansible-downloads/

configure_dock: true

dockitems_remove:
- Launchpad
- Messages
- Maps
- Photos
- FaceTime
- Contacts
- Notes
- Music
- TV
- Podcasts
- 'System Preferences'
- 'App Store'

dockitems_persist:
- name: "Terminal"
  path: "/System/Applications/Utilities/Terminal.app/"
  pos: 6
- name: "BBEdit"
  path: "/Applications/BBEdit.app/"
  pos: 7

homebrew_installed_packages:
  - ansible
  - git
  - go
  - gpg
  - grep
  - podman
  - powerline-go
  - python
  - wget
  - vim
  - zsh

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - arduino
  - nextcloud
  - raspberry-pi-imager
  - transmission
  - vlc

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 404009241, name: "BBEdit" }
  - { id: 409183694, name: "Keynote" }
  - { id: 409203825, name: "Numbers" }
  - { id: 409201541, name: "Pages" }

pip_packages:
  - name: matplotlib
  - name: numpy

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
