---
downloads: ~/.ansible-downloads/

configure_dock: true

dockitems_remove:
- Launchpad
- Messages
- Maps
- Photos
- FaceTime
- Contacts
- Notes
- Music
- TV
- Podcasts
- 'System Preferences'
- 'App Store'

dockitems_persist:
- name: "Terminal"
  path: "/System/Applications/Utilities/Terminal.app/"
  pos: 6
- name: "Visual Studio Code"
  path: "/Applications/Visual Studio Code.app/"
  pos: 7

homebrew_installed_packages:
  - ansible
  - git
  - gh
  - go
  - gpg
  - grep
  - podman
  - powerline-go
  - python
  - wget
  - vim
  - zsh

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - arduino
  - nextcloud
  - raspberry-pi-imager
  - transmission
  - visual-studio-code
  - vlc

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 1365531024, name: "1Blocker" }
  - { id: 462058435, name: "Microsoft Excel" }
  - { id: 985367838, name: "Microsoft Outlook" }
  - { id: 462062816, name: "Microsoft Powerpoint" }
  - { id: 462054704, name: "Microsoft Word" }

pip_packages:
  - name: matplotlib
  - name: numpy

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
