- name: "Configure Virtual Machines"
  hosts: "all"
  
  handlers:

    - name: "Restart Cockpit Socket"
      ansible.builtin.service:
        name: "cockpit.socket"
        state: "restarted"
      become: true
      tags:
        - "cockpit"
        - "kvm"

  tasks:

    # Virtual Machines
    - name: "Manage Virtualization Packages"
      ansible.builtin.package:
        name:
          - "qemu-kvm-core"
          - "libvirt"
          - "virt-install"
          - "guestfs-tools"
        state: "present"
      become: true
      tags:
        - "kvm"
 
    - name: "Manage cockpit Machines Packages"
      ansible.builtin.package:
        name: "cockpit-machines"
        state: "present"
      become: true
      notify:
        - "Restart Cockpit Socket"
      tags:
        - "cockpit"
        - "kvm"

