---
- name: "Configure macOS"
  hosts: "localhost"
  connection: "local"

  vars_files:
    - config-macos.yml

  roles:
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']

  tasks:

    - name: "Check and copy dotfiles"
      tags: "dotfiles"
      block:
      # Checking for .gitconfig
      - name: "Check for .gitconfig"
        ansible.builtin.stat:
          path: ~/.gitconfig
        register: stat_gitconfig

      - name: "Copy in if not exist"
        ansible.builtin.copy:
          src: files/macos-gitconfig
          dest: ~/.gitconfig
        when: stat_gitconfig.stat.exists == False

      # Checking for .vimrc
      - name: "Check for .vimrc"
        ansible.builtin.stat:
          path: ~/.vimrc
        register: stat_vimrc

      - name: "Copy in if not exist"
        ansible.builtin.copy:
          src: files/vimrc
          dest: ~/.vimrc
        when: stat_vimrc.stat.exists == False

      # Checking for .zshrc
      - name: "Check for .zshrc"
        ansible.builtin.stat:
          path: ~/.zshrc
        register: stat_zshrc

      - name: "Copy in if not exist"
        ansible.builtin.copy:
          src: files/zshrc
          dest: ~/.zshrc
        when: stat_zshrc.stat.exists == False

  
    - name: "Settings and defaults"
      tags: "settings"
      block:
      - name: "Enable tap to click I"
        community.general.osx_defaults:
          domain: com.apple.AppleMultitouchTrackpad
          key: Clicking
          type: bool
          value: true

      - name: "Enable tap to click II"
        community.general.osx_defaults:
          host: NSGlobalDomain
          domain: com.apple.mouse
          key: tapBehavior
          type: int
          value: 1

      - name: "Enable tap to click III"
        community.general.osx_defaults:
          host: -currentHost
          domain: com.apple.mouse
          key: Clicking
          type: int
          value: 1

      - name: "Avoid creating .DS_Store files on network volumes"
        community.general.osx_defaults:
          domain: com.apple.desktopservices
          key: DSDontWriteNetworkStores
          type: bool
          value: true

      - name: "Avoid creating .DS_Store files on USB volumes"
        community.general.osx_defaults:
          domain: com.apple.desktopservices
          key: DSDontWriteUSBStores
          type: bool
          value: true

      - name: "Disable recent items in Dock"
        community.general.osx_defaults:
          domain: com.apple.dock
          key: show-recents
          type: int
          value: 0

      - name: "Disable open animmation in Dock"
        community.general.osx_defaults:
          domain: com.apple.dock
          key: launchanim
          type: bool
          value: false

      - name: "Show status bar in Finder"
        community.general.osx_defaults:
          domain: com.apple.finder
          key: ShowStatusBar
          type: bool
          value: true

      - name: "Change date format in menu"
        community.general.osx_defaults:
          domain: com.apple.menuextra.clock
          key: DateFormat
          type: string
          value: "EEE HH:mm"

      - name: "Set startup settings in Terminal"
        community.general.osx_defaults:
          domain: com.apple.terminal
          key: Startup Window Settings
          type: string
          value: Pro

      - name: "Set default settings in Terminal"
        community.general.osx_defaults:
          domain: com.apple.terminal
          key: Default Window Settings
          type: string
          value: Pro

      - name: "Autohide Dock"
        community.general.osx_defaults:
          domain: com.apple.dock
          key: autohide
          type: bool
          value: true

      - name: "Set hostname"
        ansible.builtin.hostname:
          name: macbook
          use: macos

    - block:
        - name: "Run configured post-provision ansible task files"
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks|default(omit) }}"
      tags: ['post']
