---
- name: "Configure macOS"
  hosts: "localhost"
  connection: "local"

  vars_files:
    - config-macos.yml

  roles:
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']

  tasks:

    # Checking for .gitconfig
    - name: Check for .gitconfig
      ansible.builtin.stat:
        path: ~/.gitconfig
      register: stat_gitconfig

    - name: Copy in if not exist
      ansible.builtin.copy:
        src: files/macos-gitconfig
        dest: ~/.gitconfig
      when: stat_gitconfig.stat.exists == False

    # Checking for .vimrc
    - name: Check for .vimrc
      ansible.builtin.stat:
        path: ~/.vimrc
      register: stat_vimrc

    - name: Copy in if not exist
      ansible.builtin.copy:
        src: files/vimrc
        dest: ~/.vimrc
      when: stat_vimrc.stat.exists == False

    # Checking for .zshrc
    - name: Check for .zshrc
      ansible.builtin.stat:
        path: ~/.zshrc
      register: stat_zshrc

    - name: Copy in if not exist
      ansible.builtin.copy:
        src: files/zshrc
        dest: ~/.zshrc
      when: stat_zshrc.stat.exists == False

    - name: Enable tap to click
      community.general.osx_defaults:
        domain: com.apple.AppleMultitouchTrackpad
        key: Clicking
        type: int
        value: 1

    - name: Set startup settings in Terminal
      community.general.osx_defaults:
        domain: com.apple.terminal
        key: Startup Window Settings
        type: string
        value: Pro

    - name: Set default settings in Terminal
      community.general.osx_defaults:
        domain: com.apple.terminal
        key: Default Window Settings
        type: string
        value: Pro

    - name: Set hostname
      ansible.builtin.hostname:
        name: macbook
        use: macos

#    - name: Get current Terminal profile.
#      command: defaults read com.apple.terminal 'Default Window Settings'
#      register: terminal_theme
#      changed_when: false
#      check_mode: false

#    - name: Ensure default Terminal profile is set to Pro.
#      command: "{{ item }}"
#      with_items:
#        - defaults write com.apple.terminal 'Default Window Settings' -string Pro
#        - defaults write com.apple.terminal 'Startup Window Settings' -string Pro
#      changed_when: false
#      when: "'Pro' not in terminal_theme.stdout"

    - block:
        - name: Run configured post-provision ansible task files.
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks|default(omit) }}"
      tags: ['post']
